#Default Excel Diff & Merge Viewer Configuration
#Sun Aug 16 17:11:50 IST 2026
excel.ours.name=OURS.xlsx
excel.output.name=Compared.xlsx
excel.theirs.name=THEIRS.xlsx
folder.excel=resources/excel
folder.reports=resources/reports
report.json.name=comparison.json
report.text.name=report.txt


file.retry.max=5
file.retry.delay.ms=2000